version: "3.8"

services:
  db:
    image: chinnalaharika/pyapp:db_image
    ports:
      - "3306:3306"
    deploy:
      replicas: 1
    networks:
      - appnet

  auth_service:
    image: chinnalaharika/pyapp:auth_image
    ports:
      - "5001:5001"
    deploy:
      replicas: 1
    networks:
      - appnet

  book_service:
    image: chinnalaharika/pyapp:book_image
    ports:
      - "5002:5002"
    deploy:
      replicas: 1
    networks:
      - appnet

  borrow_service:
    image: chinnalaharika/pyapp:borrow_image
    ports:
      - "5003:5003"
    deploy:
      replicas: 1
    networks:
      - appnet

  app_service:
    image: chinnalaharika/pyapp:frontend
    ports:
      - "5000:5000"
    deploy:
      replicas: 1
    networks:
      - appnet

networks:
  appnet:
    driver: overlay
